FROM node:18-alpine

# Create an app directory
WORKDIR /app

#Install app dependancies
COPY ./package*.json ./

# Run npm install
RUN npm install

COPY ./server.js .
COPY ./connection.js .
COPY ./.env .

EXPOSE 3000

CMD [ "npm", "start"]