services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: CEID_RESCUE_PROGRAM
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - 3306:3306
    networks:
      - mynetwork
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d

  server:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    container_name: rescueTeamServer
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    volumes:
      - ./website:/app/website

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: test_user
      PMA_PASSWORD: test_password
    ports:
      - "8080:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
