DROP DATABASE IF EXISTS CEID_RESCUE_PROGRAM;
CREATE DATABASE IF NOT EXISTS CEID_RESCUE_PROGRAM;
USE CEID_RESCUE_PROGRAM;

CREATE TABLE IF NOT EXISTS SESSIONS (
    session_id varchar(128) PRIMARY KEY NOT NULL,
    expires    int(11)                  NOT NULL,
    data       text
);
